# Generated by Django 4.2 on 2023-06-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=64)),
                ("detail", models.TextField(default="", null=True)),
                ("writer", models.CharField(max_length=64)),
                (
                    "category",
                    models.CharField(
                        choices=[("FAQ", "FAQ"), ("Inquiry", "Inquiry")], max_length=50
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commenter", models.CharField(max_length=64)),
                ("comment", models.TextField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="boards.post"
                    ),
                ),
            ],
        ),
    ]
